# Energy Prediction

# Prepeation

### Imports

In [46]:
import os
import warnings
import time
import tempfile
import mlflow
import mlflow.sklearn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns
import scipy.stats as stats
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, SGDRegressor, HuberRegressor, TheilSenRegressor, RANSACRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, BaggingRegressor, ExtraTreesRegressor
from sklearn.svm import SVR
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.neighbors import KNeighborsRegressor
warnings.filterwarnings('ignore')
from sklearn.preprocessing import OneHotEncoder

### Gitlab Experiments Config

In [42]:
os.environ["MLFLOW_TRACKING_TOKEN"]='glpat-BDJx7ocbJsisiGoTAzcD'
os.environ["MLFLOW_TRACKING_URI"]='https://gitlab.reutlingen-university.de/api/v4/projects/3206/ml/mlflow'

### Data Prpereation

In [13]:
df = pd.read_csv('data/training-data/energy_predcition_training-data.csv')
df['model'] = df['model'].astype('category')

In [4]:
encoder = OneHotEncoder(sparse=False)
model_encoded = encoder.fit_transform(df[['model']])
model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
df_encoded = pd.concat([df, model_encoded_df], axis=1).drop('model', axis=1)

X_encoded = df_encoded.drop('energy_consumed', axis=1)
y_encoded = df_encoded['energy_consumed']

# Aufteilung in Trainings- und Testdatensatz
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=0)

In [37]:
X_train

,num_num_features,num_cat_features,number_of_instances,model_0,model_1,model_2,model_3,model_4
4901,5,8,200000.0,0.0,0.0,1.0,0.0,0.0
4872,6,13,150000.0,0.0,0.0,1.0,0.0,0.0
6697,5,6,150000.0,0.0,1.0,0.0,0.0,0.0
12487,1,8,27126.6,1.0,0.0,0.0,0.0,0.0
12549,0,0,9042.2,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4859,1,0,50000.0,0.0,0.0,1.0,0.0,0.0
3264,1,4,50000.0,0.0,0.0,0.0,0.0,1.0
9845,1,5,45211.0,0.0,0.0,1.0,0.0,0.0
10799,2,4,9042.2,0.0,1.0,0.0,0.0,0.0
2732,2,4,150000.0,0.0,0.0,0.0,0.0,1.0

## Helper functions

In [88]:
# Mit Umwandlung
import pandas as pd

def predict_energy_consumption_new(model, encoder, num_num_features, num_cat_features, number_of_instances, model_category):
    def format_energy(value_in_kwh):
        units = [
            ("TWh", 1e-9),   
            ("GWh", 1e-6),   
            ("MWh", 1e-3),  
            ("kWh", 1),   
            ("Wh", 1e3),   
            ("mWh", 1e6),    
            ("µWh", 1e9),   
            ("nWh", 1e12),   
            ("pWh", 1e15)]
        
        for unit, factor in units:
            if value_in_kwh * factor >= 1:
                return f"{value_in_kwh * factor:.2f} {unit}"

        return "0 µWh"  # Falls der Wert zu klein ist

    input_data = pd.DataFrame({
        'num_num_features': [num_num_features],
        'num_cat_features': [num_cat_features],
        'number_of_instances': [number_of_instances],
        'model': [model_category]
    })

    model_encoded = encoder.transform(input_data[['model']])
    model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
    input_data_encoded = pd.concat([input_data.drop('model', axis=1), model_encoded_df], axis=1)
    predicted_energy_consumption = model.predict(input_data_encoded)

    return format_energy(predicted_energy_consumption[0])

## Model Training

### Linear regression

In [100]:
import mlflow
from sklearn.linear_model import LinearRegression
import tempfile

mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='linearregression_candidate'):
    li_model = LinearRegression()
    li_model.fit(X_test, y_test)

    y_pred = li_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 15:24:55 INFO mlflow.tracking.fluent: Experiment with name 'Baseline Experiement Energy Prediction' does not exist. Creating a new experiment.
2024/01/10 15:24:59 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/290/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

Wie die Modelle eingegben werden müssen:

model_mapping = {
    'decision_tree': 0.0,
    'gaussian_nb': 1.0,
    'knn': 2.0,
    'logistic_regression': 3.0,
    'random_forest': 4.0
}

In [199]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=5,
    num_cat_features=12,
    number_of_instances=40000,
    model_category=4
)

example_prediction

'68.15 mWh'

In [200]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=50,
    num_cat_features=12,
    number_of_instances=40,
    model_category=1
)

example_prediction

'124.75 mWh'

In [201]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=50,
    num_cat_features=102,
    number_of_instances=40,
    model_category=1
)

example_prediction

'157.65 mWh'

In [202]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=50,
    num_cat_features=12,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'141.21 Wh'

In [204]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=50,
    num_cat_features=50,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'141.22 Wh'

In [205]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=80,
    num_cat_features=50,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'141.30 Wh'

In [206]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=50,
    num_cat_features=80,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'141.23 Wh'

In [207]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=500,
    num_cat_features=200,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'142.47 Wh'

In [208]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=5000,
    num_cat_features=200,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'154.39 Wh'

In [209]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=5000,
    num_cat_features=2000,
    number_of_instances=4000000000,
    model_category=1
)

example_prediction

'155.05 Wh'

## Random Forrest

In [105]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='randomforrest_candidate'):
    rf_model = RandomForestRegressor()
    rf_model.fit(X_test, y_test)

    y_pred = rf_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 15:30:47 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/292/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [108]:
example_prediction = predict_energy_consumption_new(
    model=rf_model,
    encoder=encoder,
    num_num_features=5,
    num_cat_features=12,
    number_of_instances=40000,
    model_category=1
)

example_prediction

'357.18 µWh'

In [109]:
example_prediction = predict_energy_consumption_new(
    model=rf_model,
    encoder=encoder,
    num_num_features=5444,
    num_cat_features=124444444444444,
    number_of_instances=40,
    model_category=1
)

example_prediction

'242.75 µWh'

## GradientBoostingRegressor

In [123]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='gradientboostingregressor_candidate'):
    gbr_model = GradientBoostingRegressor()
    gbr_model.fit(X_test, y_test)

    y_pred = gbr_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 15:37:55 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/295/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [124]:
example_prediction = predict_energy_consumption_new(
    model=gbr_model,
    encoder=encoder,
    num_num_features=5,
    num_cat_features=12,
    number_of_instances=40000,
    model_category=1
)

example_prediction

'3.47 mWh'

In [125]:
example_prediction = predict_energy_consumption_new(
    model=gbr_model,
    encoder=encoder,
    num_num_features=500000000,
    num_cat_features=1000002,
    number_of_instances=40000,
    model_category=1
)

example_prediction

'2.50 mWh'

## 	DecisionTreeRegressor

In [142]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='decisiontreeregressor_candidate'):
    dt_model = DecisionTreeRegressor()
    dt_model.fit(X_test, y_test)

    y_pred = dt_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 15:44:36 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/301/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [143]:
example_prediction = predict_energy_consumption_new(
    model=dt_model,
    encoder=encoder,
    num_num_features=5,
    num_cat_features=12,
    number_of_instances=40000,
    model_category=1
)

example_prediction

'371.71 µWh'

In [144]:
example_prediction = predict_energy_consumption_new(
    model=dt_model,
    encoder=encoder,
    num_num_features=500000000,
    num_cat_features=1000002,
    number_of_instances=40000,
    model_category=1
)

example_prediction

'394.19 µWh'

## GaussianProcessRegressor

In [139]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='gaussianprocessregressor_candidate'):
    gpr_model = GaussianProcessRegressor()
    gpr_model.fit(X_test, y_test)

    y_pred = gpr_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 15:43:43 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/300/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [140]:
example_prediction = predict_energy_consumption_new(
    model=gpr_model,
    encoder=encoder,
    num_num_features=500,
    num_cat_features=12,
    number_of_instances=400,
    model_category=1
)

example_prediction

'0 µWh'

In [141]:
example_prediction = predict_energy_consumption_new(
    model=gpr_model,
    encoder=encoder,
    num_num_features=500000000,
    num_cat_features=1000002,
    number_of_instances=400000000000,
    model_category=1
)

example_prediction

'0 µWh'

## Ridge

In [148]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='ridge_candidate'):
    ridge_model = Ridge(alpha=1.0, solver='auto') 
    ridge_model.fit(X_test, y_test)

    y_pred = ridge_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 15:54:29 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/303/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [149]:
example_prediction = predict_energy_consumption_new(
    model=ridge_model,
    encoder=encoder,
    num_num_features=500,
    num_cat_features=12,
    number_of_instances=400,
    model_category=1
)

example_prediction

'1.32 Wh'

In [167]:
example_prediction = predict_energy_consumption_new(
    model=ridge_model,
    encoder=encoder,
    num_num_features=50000,
    num_cat_features=100002,
    number_of_instances=400000000,
    model_category=4
)

example_prediction

'183.23 Wh'

## Poly

In [151]:
from sklearn.preprocessing import PolynomialFeatures

In [172]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='poly_3_candidate'):
    
    poly_degree = 3
    poly_features = PolynomialFeatures(degree=poly_degree)
    X_train_poly = poly_features.fit_transform(X_train)
    X_test_poly = poly_features.transform(X_test)

    poly_2_model = LinearRegression()
    # Trainieren des Modells mit Trainingsdaten
    poly_2_model.fit(X_train_poly, y_train)

    # Vorhersagen mit Testdaten
    y_pred = poly_2_model.predict(X_test_poly)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    # Protokollieren des Modells in MLflow
    mlflow.sklearn.log_model(poly_2_model, "") # Verwendung von poly_2_model anstelle von model

2024/01/10 15:58:20 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/308/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [173]:
example_prediction = predict_energy_consumption_new(
    model=eln_model,
    encoder=encoder,
    num_num_features=500,
    num_cat_features=12,
    number_of_instances=400,
    model_category=1
)

example_prediction

'14.35 mWh'

In [174]:
example_prediction = predict_energy_consumption_new(
    model=eln_model,
    encoder=encoder,
    num_num_features=500000000,
    num_cat_features=1000002,
    number_of_instances=400000000000,
    model_category=1
)

example_prediction

'14.35 mWh'

## SVR

In [193]:
mlflow.set_experiment(experiment_name="Baseline Experiement Energy Prediction")

with mlflow.start_run(run_name='supportvectorregressor_linear_candidate'):
    param_grid = {
        'C': [0.1, 1, 10, 100],
        'kernel': ['linear'],  # Fokussieren auf linearen Kernel
        'gamma': ['scale', 'auto'],
        'epsilon': [0.01, 0.1, 0.5, 1]
    }
    svr = SVR()
    grid_search = GridSearchCV(svr, param_grid, cv=5, scoring='neg_mean_squared_error')
    
    grid_search.fit(X_train, y_train)
    
    best_svr = grid_search.best_estimator_
    y_pred = best_svr.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(model, "")

2024/01/10 16:11:58 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_19/311/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [197]:
example_prediction = predict_energy_consumption_new(
    model=eln_model,
    encoder=encoder,
    num_num_features=50,
    num_cat_features=12,
    number_of_instances=40,
    model_category=2
)

example_prediction

'14.35 mWh'

In [246]:
example_prediction = predict_energy_consumption_new(
    model=eln_model,
    encoder=encoder,
    num_num_features=500000,
    num_cat_features=10000,
    number_of_instances=400000000000,
    model_category=1
)

example_prediction

'14.35 mWh'

# Neues Modell

In [380]:
import joblib
joblib.dump((li_model, rf_model), 'ml_model_package.pkl')

['ml_model_package.pkl']

# Erweiterte tests

## Test 1 - Daten logarithmisch transformieren

In [75]:
encoder = OneHotEncoder(sparse=False)
model_encoded = encoder.fit_transform(df[['model']])
model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
df_encoded = pd.concat([df, model_encoded_df], axis=1).drop('model', axis=1)

X_encoded = df_encoded.drop('energy_consumed', axis=1)
y_encoded = df_encoded['energy_consumed']

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=0)

numeric_cols = ['num_num_features', 'num_cat_features', 'number_of_instances'] 

# Logarithmisch transformieren
for col in numeric_cols:
    X_train[col] = np.log1p(X_train[col])
    X_test[col] = np.log1p(X_test[col])

In [76]:
X_train

,num_num_features,num_cat_features,number_of_instances,model_0,model_1,model_2,model_3,model_4
210,1.098612,2.079442,12.676079,0.0,0.0,0.0,1.0,0.0
6748,0.000000,0.693147,11.512935,0.0,1.0,0.0,0.0,0.0
7995,1.386294,2.302585,10.719118,0.0,0.0,0.0,0.0,1.0
7470,0.693147,1.098612,12.429220,1.0,0.0,0.0,0.0,0.0
4134,1.945910,2.708050,10.819798,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
4859,0.693147,0.000000,10.819798,0.0,0.0,1.0,0.0,0.0
3264,0.693147,1.609438,10.819798,0.0,0.0,0.0,0.0,1.0
9845,0.693147,1.791759,10.719118,0.0,0.0,1.0,0.0,0.0
10799,1.098612,1.609438,9.109768,0.0,1.0,0.0,0.0,0.0
2732,1.098612,1.609438,11.918397,0.0,0.0,0.0,0.0,1.0

In [77]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
import mlflow
from sklearn.linear_model import LinearRegression

mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features")

with mlflow.start_run(run_name='linearregression_candidate'):
    li_model = LinearRegression()
    li_model.fit(X_test, y_test)

    y_pred = li_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(li_model, "")

2024/01/11 11:09:35 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_20/324/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2024/01/11 11:09:35 DEBUG mlflow.models.model:
Traceback (most recent call last):
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/models/model.py", line 622, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1331, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1770, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 494, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 327, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': '404 Not Found'}

In [79]:
predict_energy_consumption_new(li_model, encoder, 1000, 1000, 50000000, 4)

'169.55 Wh'

In [39]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features")

with mlflow.start_run(run_name='randomforrest_candidate'):
    rf_model = RandomForestRegressor()
    rf_model.fit(X_test, y_test)

    y_pred = rf_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(rf_model, "")

2024/01/11 10:57:25 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_20/317/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2024/01/11 10:57:25 DEBUG mlflow.models.model:
Traceback (most recent call last):
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/models/model.py", line 622, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1331, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1770, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 494, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 327, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': '404 Not Found'}

In [65]:
predict_energy_consumption_new(rf_model, encoder, 100, 5000, 100, 1)

'241.30 µWh'

## Test 1 - Daten logarithmisch transformieren + Extremwert simulation

In [82]:
# Extremfälle definieren
extreme_cases = pd.DataFrame({
    'num_num_features': [1000, 1000, 1000, 1000, 1000],
    'num_cat_features': [1000, 1000, 1000, 1000, 1000],
    'number_of_instances': [50000000, 50000000, 50000000, 50000000, 50000000],
    'model': [0, 1, 2, 3, 4],
    'energy_consumed': [0.8, 0.65, 0.75, 1.8, 2.7]
})

df = pd.concat([df, extreme_cases], ignore_index=True)

encoder = OneHotEncoder(sparse=False)
model_encoded = encoder.fit_transform(df[['model']])
model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
df_encoded = pd.concat([df, model_encoded_df], axis=1).drop('model', axis=1)

X_encoded = df_encoded.drop('energy_consumed', axis=1)
y_encoded = df_encoded['energy_consumed']

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=0)

numeric_cols = ['num_num_features', 'num_cat_features', 'number_of_instances'] 

# Logarithmisch transformieren
for col in numeric_cols:
    X_train[col] = np.log1p(X_train[col])
    X_test[col] = np.log1p(X_test[col])

In [85]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
import mlflow
from sklearn.linear_model import LinearRegression

mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features extreme values")

with mlflow.start_run(run_name='linearregression_candidate'):
    li_model = LinearRegression()
    li_model.fit(X_test, y_test)

    y_pred = li_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(li_model, "")

2024/01/11 11:11:33 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_21/327/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2024/01/11 11:11:33 DEBUG mlflow.models.model:
Traceback (most recent call last):
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/models/model.py", line 622, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1331, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1770, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 494, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 327, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': '404 Not Found'}

In [84]:
predict_energy_consumption_new(li_model, encoder, 1000, 1000, 50000000, 4)

'367.00 Wh'

In [86]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features extreme values")

with mlflow.start_run(run_name='randomforrest_candidate'):
    rf_model = RandomForestRegressor()
    rf_model.fit(X_test, y_test)

    y_pred = rf_model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(rf_model, "")

2024/01/11 11:12:43 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_21/328/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2024/01/11 11:12:43 DEBUG mlflow.models.model:
Traceback (most recent call last):
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/models/model.py", line 622, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1331, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1770, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 494, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 327, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': '404 Not Found'}

In [128]:
predict_energy_consumption_new(rf_model, encoder, 100, 100, 500, 4)

'1.25 kWh'

In [99]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features extreme values")

with mlflow.start_run(run_name='supportvectorregressor_rbf_candidate'):
    svr = SVR(kernel='rbf')

    svr.fit(X_train, y_train)
    
    y_pred_scaled = svr.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(svr, "")

2024/01/11 11:21:25 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_21/331/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2024/01/11 11:21:25 DEBUG mlflow.models.model:
Traceback (most recent call last):
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/models/model.py", line 622, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1331, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1770, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 494, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 327, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': '404 Not Found'}

In [110]:
predict_energy_consumption_new(svr, encoder, 10, 10, 50000, 4)

'60.53 Wh'

In [111]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features extreme values")

with mlflow.start_run(run_name='supportvectorregressor_sigmoid_candidate'):
    svr = SVR(kernel='sigmoid')

    svr.fit(X_train, y_train)
    
    y_pred_scaled = svr.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(svr, "")

2024/01/11 11:24:06 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_21/332/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.
2024/01/11 11:24:06 DEBUG mlflow.models.model:
Traceback (most recent call last):
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/models/model.py", line 622, in log
    mlflow.tracking.fluent._record_logged_model(mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1331, in _record_logged_model
    MlflowClient()._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1770, in _record_logged_model
    self._tracking_client._record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 494, in _record_logged_model
    self.store.record_logged_model(run_id, mlflow_model)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 327, in record_logged_model
    self._call_endpoint(LogModel, req_body)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 219, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/lukasgrodmeier/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mlflow/utils/rest_utils.py", line 151, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INTERNAL_ERROR: Response: {'error': '404 Not Found'}

In [114]:
predict_energy_consumption_new(svr, encoder, 10, 10, 500, 1)

'177181388718382704932945920.00 TWh'

In [131]:
logging.getLogger("mlflow").setLevel(logging.WARNING)
mlflow.set_experiment(experiment_name="Logarithmic Transformation numeric Features extreme values")

with mlflow.start_run(run_name='supportvectorregressor_linear_candidate'):
    svr = SVR(kernel='linear')

    svr.fit(X_train, y_train)
    
    y_pred_scaled = svr.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    mlflow.log_metric('mse', mse)
    mlflow.log_metric('r2', r2)

    mlflow.sklearn.log_model(svr, "")

2024/01/11 11:31:32 WARNING mlflow.models.model: Logging model metadata to the tracking server has failed. The model artifacts have been logged successfully under https://gitlab.reutlingen-university.de/api/v4/projects/3206/packages/generic/ml_experiment_21/335/. Set logging level to DEBUG via `logging.getLogger("mlflow").setLevel(logging.DEBUG)` to see the full traceback.

In [129]:
predict_energy_consumption_new(svr, encoder, 100, 100, 50, 4)

'409.64 Wh'

# Sonstiges

In [231]:
# Konstanten Term von Linearer Regression
constant_term = li_model.intercept_
constant_term

3.757250470513284e-06

In [358]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=1000,
    num_cat_features=1000,
    number_of_instances=50000000,
    model_category=4
)

example_prediction

'4.83 Wh'

In [ ]:
encoder = OneHotEncoder(sparse=False)
model_encoded = encoder.fit_transform(df[['model']])
model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
df_encoded = pd.concat([df, model_encoded_df], axis=1).drop('model', axis=1)

X_encoded = df_encoded.drop('energy_consumed', axis=1)
y_encoded = df_encoded['energy_consumed']

# Aufteilung in Trainings- und Testdatensatz
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y_encoded, test_size=0.2, random_state=0)

In [359]:
import numpy as np
import pandas as pd

# Laden der Daten
file_path = 'data/training-data/energy_predcition_training-data.csv'
data = pd.read_csv(file_path)

# Extremfälle definieren
extreme_cases_1 = pd.DataFrame({
    'num_num_features': [1000, 1000, 1000, 1000, 1000],
    'num_cat_features': [1000, 1000, 1000, 1000, 1000],
    'number_of_instances': [50000000, 50000000, 50000000, 50000000, 50000000],
    'model': [0, 1, 2, 3, 4],
    'energy_consumed': [0.5, 0.45, 0.55, 0.6, 0.7]
})


full_data = pd.concat([data, extreme_cases_1, extreme_cases_2], ignore_index=True)

encoder = OneHotEncoder(sparse=False)
model_encoded = encoder.fit_transform(full_data[['model']])
model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
df_extreme_encoded = pd.concat([full_data, model_encoded_df], axis=1).drop('model', axis=1)

X = df_extreme_encoded.drop('energy_consumed', axis=1)
y = df_extreme_encoded['energy_consumed']

random_forest = RandomForestRegressor(n_estimators=100, random_state=42)

# Trainingsdaten, die die Extremfälle enthalten
train_indices = np.random.choice(len(X), size=int(0.8 * len(X)), replace=False)
test_indices = np.setdiff1d(np.arange(len(X)), train_indices)

X_train, X_test = X.iloc[train_indices], X.iloc[test_indices]
y_train, y_test = y.iloc[train_indices], y.iloc[test_indices]

random_forest.fit(X_train, y_train)

# Vorhersagen für Testdaten
y_pred = random_forest.predict(X_test)

# Evaluierung des Modells
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R^2:", r2)
print("MAE:", mae)
print("MSE:", mse)

R^2: 0.9508051969516257
MAE: 0.021650138833431917
MSE: 0.5895004129360373

In [378]:
example_prediction = predict_energy_consumption_new(
    model=random_forest,
    encoder=encoder,
    num_num_features=1000,
    num_cat_features=1000,
    number_of_instances=50000000,
    model_category=0
)

example_prediction

'2.66 kWh'

In [361]:
example_prediction = predict_energy_consumption_new(
    model=rf_model,
    encoder=encoder,
    num_num_features=200,
    num_cat_features=1000,
    number_of_instances=500000,
    model_category=4
)

example_prediction

'300.50 mWh'

In [362]:
example_prediction = predict_energy_consumption_new(
    model=li_model,
    encoder=encoder,
    num_num_features=200,
    num_cat_features=1000,
    number_of_instances=500000,
    model_category=4
)

example_prediction

'962.18 mWh'

In [381]:
X_train

,num_num_features,num_cat_features,number_of_instances,model_0,model_1,model_2,model_3,model_4
8198,1,9,18084.4,0.0,0.0,0.0,0.0,1.0
11522,3,7,27126.6,0.0,1.0,0.0,0.0,0.0
3058,0,4,100000.0,0.0,0.0,0.0,0.0,1.0
642,2,6,192000.0,0.0,0.0,0.0,1.0,0.0
9337,3,8,27126.6,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
6909,2,9,50000.0,1.0,0.0,0.0,0.0,0.0
8781,2,5,36168.8,0.0,0.0,0.0,1.0,0.0
5183,7,13,100000.0,0.0,0.0,1.0,0.0,0.0
255,4,13,320000.0,0.0,0.0,0.0,1.0,0.0
9393,1,3,18084.4,0.0,0.0,0.0,1.0,0.0

In [26]:
import pandas as pd
import numpy as np

def predict_energy_consumption_new(model, encoder, num_num_features, num_cat_features, number_of_instances, model_category):
    def format_energy(value_in_kwh):
        units = [
            ("TWh", 1e-9),   
            ("GWh", 1e-6),   
            ("MWh", 1e-3),  
            ("kWh", 1),   
            ("Wh", 1e3),   
            ("mWh", 1e6),    
            ("µWh", 1e9),   
            ("nWh", 1e12),   
            ("pWh", 1e15)]
        
        for unit, factor in units:
            if value_in_kwh * factor >= 1:
                return f"{value_in_kwh * factor:.2f} {unit}"

        return "0 µWh"  # Falls der Wert zu klein ist
        
        
    # Korrekte Definition von input_data
    input_data = pd.DataFrame({
        'num_num_features': [num_num_features],
        'num_cat_features': [num_cat_features],
        'number_of_instances': [number_of_instances],
        'model': [model_category]
    })

    # Logarithmische Transformation der numerischen Features
    numeric_cols = ['num_num_features', 'num_cat_features', 'number_of_instances'] # Anpassen, falls notwendig
    for col in numeric_cols:
        input_data[col] = np.log1p(input_data[col])

    # Kodieren der kategorischen Features
    model_encoded = encoder.transform(input_data[['model']])
    model_encoded_df = pd.DataFrame(model_encoded, columns=["model_"+str(int(i)) for i in range(model_encoded.shape[1])])
    input_data_encoded = pd.concat([input_data.drop('model', axis=1), model_encoded_df], axis=1)

    # Vorhersage durchführen
    predicted_log_energy_consumption = model.predict(input_data_encoded)

    # Rücktransformation, falls die Zielvariable logarithmisch transformiert wurde
    predicted_energy_consumption = np.expm1(predicted_log_energy_consumption[0])

    return format_energy(predicted_energy_consumption)